weather_conditions: {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",

  45: "Fog",
  48: "Depositing rime fog",

  51: "Light drizzle",
  53: "Moderate drizzle",
  55: "Dense drizzle",

  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",

  80: "Rain showers",
  81: "Moderate showers",
  82: "Violent showers",

  95: "Thunderstorm",
  96: "Thunderstorm with hail",
  99: "Severe thunderstorm with hail"
}

schema:
  city: object
  country: object
  date: datetime64[ns]
  extracted_at: datetime64[ns]
  temp_max: float
  temp_min: float
  temp_max_3day_avg: float
  temp_min_3day_avg: float
  temp_max_7day_avg: float
  temp_min_7day_avg: float
  weather_code: int64
  weather_desc: object
  precipitation: float